vich_uploader:
    db_driver: orm

    mappings:
        ventures:
            uri_prefix: /images/ventures
            upload_destination: '%kernel.project_dir%/public/assets/images/ventures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
